import mysql.connector
from tkinter import messagebox

def obtener_conexion():
    try:
        conexion = mysql.connector.connect(
                host="localhost",
                user="sofia", #PONER SU PROPIO USUARIO
                password="12345", #PONER SU PROPIA CLAVE
                database="recupero_obra_social")
        print("Conexión exitosa")
        return conexion
    except mysql.connector.Error as err:
        messagebox.showerror("Error de Conexión", f"No se pudo conectar a la base de datos: {err}")
        return None
    

def insertar_paciente(nombre, dni, obrasocial, obrasocialsec, propietario, fechanac, sexo, telefonopaciente, contactoemergencia, numeroafiliado):
    conexion = obtener_conexion()
    if conexion is None:
        return
    try:
        cursor = conexion.cursor()
        sql = "INSERT INTO paciente (nombre, apellido, matricula, telefono, documento) VALUES (%s, %s, %s, %s, %s)"
        val = (nombre, dni, obrasocial, obrasocialsec, propietario, fechanac, sexo, telefonopaciente, contactoemergencia, numeroafiliado)
        cursor.execute(sql, val)
        conexion.commit()
        messagebox.showinfo("Éxito", "Registro insertado correctamente.")
    except mysql.connector.Error as err:
        messagebox.showerror("Error", f"Error al insertar en la base de datos: {err}")
    finally:
        conexion.close()

def actualizar_paciente(nombre, dni, obrasocial, obrasocialsec, propietario, fechanac, sexo, telefonopaciente, contactoemergencia, numeroafiliado):
    conexion = obtener_conexion()
    if conexion is None:
        return
    try:
        cursor = conexion.cursor()
        sql = "UPDATE paciente SET nombre=%s, apellido=%s, matricula=%s, telefono=%s, documento=%s WHERE id=%s"
        val = (nombre, dni, obrasocial, obrasocialsec, propietario, fechanac, sexo, telefonopaciente, contactoemergencia, numeroafiliado)
        cursor.execute(sql, val)
        conexion.commit()
        messagebox.showinfo("Éxito", "Registro actualizado correctamente.")
    except mysql.connector.Error as err:
        messagebox.showerror("Error", f"Error al actualizar en la base de datos: {err}")
    finally:
        conexion.close()